import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1774374830744 implements MigrationInterface {
    name = 'InitialMigration1774374830744'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "tenants" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "domain" varchar NOT NULL, "plan" varchar CHECK( "plan" IN ('free','basic','standard','premium','enterprise') ) NOT NULL DEFAULT ('free'), "subscriptionStatus" varchar CHECK( "subscriptionStatus" IN ('active','inactive','past_due','canceled') ) NOT NULL DEFAULT ('active'), "expiresAt" datetime, "stripe_customer_id" varchar, CONSTRAINT "UQ_32731f181236a46182a38c992a8" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "username" varchar NOT NULL, "password_hash" varchar NOT NULL, "password_reset_token" varchar, "password_reset_expires" datetime, "role" varchar CHECK( "role" IN ('super_admin','admin','teacher','parent') ) NOT NULL DEFAULT ('parent'), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "description" varchar)`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "role" varchar CHECK( "role" IN ('super_admin','admin','teacher','parent') ) NOT NULL, "permissionId" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "timetable_entries" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "classLevel" varchar NOT NULL, "dayOfWeek" varchar NOT NULL, "startTime" varchar NOT NULL, "endTime" varchar NOT NULL, "subjectId" varchar NOT NULL, "teacherId" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "subscription_plans" ("id" varchar PRIMARY KEY NOT NULL, "name" varchar NOT NULL, "description" varchar NOT NULL, "price" integer NOT NULL, "interval" varchar CHECK( "interval" IN ('month','year') ) NOT NULL DEFAULT ('month'), "stripePriceId" varchar NOT NULL, "features" text NOT NULL, "isActive" boolean NOT NULL DEFAULT (1), CONSTRAINT "UQ_ae18a0f6e0143f06474aa8cef1f" UNIQUE ("name"))`);
        await queryRunner.query(`CREATE TABLE "sections" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "classLevelId" varchar NOT NULL, "room" varchar)`);
        await queryRunner.query(`CREATE TABLE "class_levels" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "description" varchar)`);
        await queryRunner.query(`CREATE TABLE "academic_years" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isCurrent" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`CREATE TABLE "students" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "registrationNumber" varchar, "classLevelId" varchar, "sectionId" varchar, "academicYearId" varchar, "status" varchar NOT NULL DEFAULT ('Active'), "parentId" varchar)`);
        await queryRunner.query(`CREATE TABLE "staff" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "role" varchar NOT NULL, "email" varchar NOT NULL, "phone" varchar, CONSTRAINT "UQ_902985a964245652d5e3a0f5f6a" UNIQUE ("email"))`);
        await queryRunner.query(`CREATE TABLE "report_cards" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "studentId" varchar NOT NULL, "examinationId" varchar NOT NULL, "marks" decimal(5,2) NOT NULL, "grade" varchar, "remarks" varchar)`);
        await queryRunner.query(`CREATE TABLE "payrolls" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "staffId" varchar NOT NULL, "salary" decimal(10,2) NOT NULL, "payDate" datetime NOT NULL, "status" varchar NOT NULL DEFAULT ('unpaid'))`);
        await queryRunner.query(`CREATE TABLE "pending_payments" ("id" varchar PRIMARY KEY NOT NULL, "amount" integer NOT NULL, "method" varchar CHECK( "method" IN ('stripe','mpesa','bank_transfer') ) NOT NULL, "reference" varchar NOT NULL, "plan" varchar CHECK( "plan" IN ('free','basic','standard','premium','enterprise') ), "isApproved" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "tenantId" varchar)`);
        await queryRunner.query(`CREATE TABLE "lms_connections" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "provider" varchar CHECK( "provider" IN ('moodle','google_classroom','canvas') ) NOT NULL, "apiUrl" varchar NOT NULL, "encrypted_credential_1" varchar NOT NULL, "encrypted_credential_2" varchar, "encrypted_refresh_token" varchar, "isConnected" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a1b6fdd388caeacedb13649e72" ON "lms_connections" ("tenantId", "provider") `);
        await queryRunner.query(`CREATE TABLE "books" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "title" varchar NOT NULL, "author" varchar NOT NULL, "isbn" varchar, "status" varchar NOT NULL DEFAULT ('available'))`);
        await queryRunner.query(`CREATE TABLE "fees" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "studentId" varchar NOT NULL, "amount" decimal(10,2) NOT NULL, "dueDate" datetime NOT NULL, "status" varchar NOT NULL DEFAULT ('unpaid'))`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "category" varchar NOT NULL, "amount" decimal(10,2) NOT NULL, "date" datetime NOT NULL, "description" varchar)`);
        await queryRunner.query(`CREATE TABLE "examinations" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "subjectId" varchar NOT NULL, "date" datetime NOT NULL, "totalMarks" decimal(5,2) NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "senderId" varchar NOT NULL, "recipientId" varchar NOT NULL, "content" text NOT NULL, "sentAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`CREATE TABLE "calendar_events" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "title" varchar NOT NULL, "start" datetime NOT NULL, "end" datetime NOT NULL, "description" varchar)`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar, "userId" varchar NOT NULL, "action" varchar NOT NULL, "entity" varchar NOT NULL, "entityId" varchar, "oldValue" text, "newValue" text, "ipAddress" varchar, "userAgent" varchar, "createdAt" datetime NOT NULL DEFAULT (datetime('now')))`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "studentId" varchar NOT NULL, "classLevelId" varchar NOT NULL, "date" datetime NOT NULL, "status" varchar NOT NULL)`);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "classLevel" varchar NOT NULL, "teacherId" varchar)`);
        await queryRunner.query(`CREATE TABLE "grading_scales" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "grade" varchar NOT NULL, "minMark" decimal(5,2) NOT NULL, "maxMark" decimal(5,2) NOT NULL, "gradePoint" decimal(5,2) NOT NULL, "remarks" varchar)`);
        await queryRunner.query(`CREATE TABLE "temporary_users" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "username" varchar NOT NULL, "password_hash" varchar NOT NULL, "password_reset_token" varchar, "password_reset_expires" datetime, "role" varchar CHECK( "role" IN ('super_admin','admin','teacher','parent') ) NOT NULL DEFAULT ('parent'), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"), CONSTRAINT "FK_c58f7e88c286e5e3478960a998b" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_users"("id", "tenantId", "username", "password_hash", "password_reset_token", "password_reset_expires", "role") SELECT "id", "tenantId", "username", "password_hash", "password_reset_token", "password_reset_expires", "role" FROM "users"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`ALTER TABLE "temporary_users" RENAME TO "users"`);
        await queryRunner.query(`CREATE TABLE "temporary_permissions" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "description" varchar, CONSTRAINT "FK_866cc84ac2cdb0c362b4eb7ce3f" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_permissions"("id", "tenantId", "name", "description") SELECT "id", "tenantId", "name", "description" FROM "permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`ALTER TABLE "temporary_permissions" RENAME TO "permissions"`);
        await queryRunner.query(`CREATE TABLE "temporary_role_permissions" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "role" varchar CHECK( "role" IN ('super_admin','admin','teacher','parent') ) NOT NULL, "permissionId" varchar NOT NULL, CONSTRAINT "FK_4f9e1b4f8d012d4b8e67f9d03ef" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_06792d0c62ce6b0203c03643cdd" FOREIGN KEY ("permissionId") REFERENCES "permissions" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_role_permissions"("id", "tenantId", "role", "permissionId") SELECT "id", "tenantId", "role", "permissionId" FROM "role_permissions"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`ALTER TABLE "temporary_role_permissions" RENAME TO "role_permissions"`);
        await queryRunner.query(`CREATE TABLE "temporary_timetable_entries" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "classLevel" varchar NOT NULL, "dayOfWeek" varchar NOT NULL, "startTime" varchar NOT NULL, "endTime" varchar NOT NULL, "subjectId" varchar NOT NULL, "teacherId" varchar NOT NULL, CONSTRAINT "FK_bf05b621225fe322e16bb71e99c" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_timetable_entries"("id", "tenantId", "classLevel", "dayOfWeek", "startTime", "endTime", "subjectId", "teacherId") SELECT "id", "tenantId", "classLevel", "dayOfWeek", "startTime", "endTime", "subjectId", "teacherId" FROM "timetable_entries"`);
        await queryRunner.query(`DROP TABLE "timetable_entries"`);
        await queryRunner.query(`ALTER TABLE "temporary_timetable_entries" RENAME TO "timetable_entries"`);
        await queryRunner.query(`CREATE TABLE "temporary_sections" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "classLevelId" varchar NOT NULL, "room" varchar, CONSTRAINT "FK_90de3d8f44c25bbe2409d9e5796" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_37c6673992b9be4f89eda3763b1" FOREIGN KEY ("classLevelId") REFERENCES "class_levels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_sections"("id", "tenantId", "name", "classLevelId", "room") SELECT "id", "tenantId", "name", "classLevelId", "room" FROM "sections"`);
        await queryRunner.query(`DROP TABLE "sections"`);
        await queryRunner.query(`ALTER TABLE "temporary_sections" RENAME TO "sections"`);
        await queryRunner.query(`CREATE TABLE "temporary_class_levels" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "description" varchar, CONSTRAINT "FK_a11a6669a2504971ef9bbea92d5" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_class_levels"("id", "tenantId", "name", "description") SELECT "id", "tenantId", "name", "description" FROM "class_levels"`);
        await queryRunner.query(`DROP TABLE "class_levels"`);
        await queryRunner.query(`ALTER TABLE "temporary_class_levels" RENAME TO "class_levels"`);
        await queryRunner.query(`CREATE TABLE "temporary_academic_years" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isCurrent" boolean NOT NULL DEFAULT (0), CONSTRAINT "FK_6396255f077c8a9ce1e08d72560" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_academic_years"("id", "tenantId", "name", "startDate", "endDate", "isCurrent") SELECT "id", "tenantId", "name", "startDate", "endDate", "isCurrent" FROM "academic_years"`);
        await queryRunner.query(`DROP TABLE "academic_years"`);
        await queryRunner.query(`ALTER TABLE "temporary_academic_years" RENAME TO "academic_years"`);
        await queryRunner.query(`CREATE TABLE "temporary_students" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "registrationNumber" varchar, "classLevelId" varchar, "sectionId" varchar, "academicYearId" varchar, "status" varchar NOT NULL DEFAULT ('Active'), "parentId" varchar, CONSTRAINT "FK_0fe5a6912f421e1c20615814426" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_cc72cc8834265d839084cc07d3c" FOREIGN KEY ("classLevelId") REFERENCES "class_levels" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_f0ced4971b8819fe0dcca3157e8" FOREIGN KEY ("sectionId") REFERENCES "sections" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_de076eb45af95b68abe8f199083" FOREIGN KEY ("academicYearId") REFERENCES "academic_years" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_students"("id", "tenantId", "firstName", "lastName", "registrationNumber", "classLevelId", "sectionId", "academicYearId", "status", "parentId") SELECT "id", "tenantId", "firstName", "lastName", "registrationNumber", "classLevelId", "sectionId", "academicYearId", "status", "parentId" FROM "students"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`ALTER TABLE "temporary_students" RENAME TO "students"`);
        await queryRunner.query(`CREATE TABLE "temporary_staff" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "role" varchar NOT NULL, "email" varchar NOT NULL, "phone" varchar, CONSTRAINT "UQ_902985a964245652d5e3a0f5f6a" UNIQUE ("email"), CONSTRAINT "FK_c4f42a7776a2fd07edf070e3953" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_staff"("id", "tenantId", "firstName", "lastName", "role", "email", "phone") SELECT "id", "tenantId", "firstName", "lastName", "role", "email", "phone" FROM "staff"`);
        await queryRunner.query(`DROP TABLE "staff"`);
        await queryRunner.query(`ALTER TABLE "temporary_staff" RENAME TO "staff"`);
        await queryRunner.query(`CREATE TABLE "temporary_report_cards" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "studentId" varchar NOT NULL, "examinationId" varchar NOT NULL, "marks" decimal(5,2) NOT NULL, "grade" varchar, "remarks" varchar, CONSTRAINT "FK_060ad419c691fd5f45ea693cedb" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_report_cards"("id", "tenantId", "studentId", "examinationId", "marks", "grade", "remarks") SELECT "id", "tenantId", "studentId", "examinationId", "marks", "grade", "remarks" FROM "report_cards"`);
        await queryRunner.query(`DROP TABLE "report_cards"`);
        await queryRunner.query(`ALTER TABLE "temporary_report_cards" RENAME TO "report_cards"`);
        await queryRunner.query(`CREATE TABLE "temporary_payrolls" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "staffId" varchar NOT NULL, "salary" decimal(10,2) NOT NULL, "payDate" datetime NOT NULL, "status" varchar NOT NULL DEFAULT ('unpaid'), CONSTRAINT "FK_817125701cf8239a5a6a9de2e9c" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_payrolls"("id", "tenantId", "staffId", "salary", "payDate", "status") SELECT "id", "tenantId", "staffId", "salary", "payDate", "status" FROM "payrolls"`);
        await queryRunner.query(`DROP TABLE "payrolls"`);
        await queryRunner.query(`ALTER TABLE "temporary_payrolls" RENAME TO "payrolls"`);
        await queryRunner.query(`CREATE TABLE "temporary_pending_payments" ("id" varchar PRIMARY KEY NOT NULL, "amount" integer NOT NULL, "method" varchar CHECK( "method" IN ('stripe','mpesa','bank_transfer') ) NOT NULL, "reference" varchar NOT NULL, "plan" varchar CHECK( "plan" IN ('free','basic','standard','premium','enterprise') ), "isApproved" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "tenantId" varchar, CONSTRAINT "FK_0bf2c3572b7c4cb160c410dd53d" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_pending_payments"("id", "amount", "method", "reference", "plan", "isApproved", "createdAt", "updatedAt", "tenantId") SELECT "id", "amount", "method", "reference", "plan", "isApproved", "createdAt", "updatedAt", "tenantId" FROM "pending_payments"`);
        await queryRunner.query(`DROP TABLE "pending_payments"`);
        await queryRunner.query(`ALTER TABLE "temporary_pending_payments" RENAME TO "pending_payments"`);
        await queryRunner.query(`DROP INDEX "IDX_a1b6fdd388caeacedb13649e72"`);
        await queryRunner.query(`CREATE TABLE "temporary_lms_connections" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "provider" varchar CHECK( "provider" IN ('moodle','google_classroom','canvas') ) NOT NULL, "apiUrl" varchar NOT NULL, "encrypted_credential_1" varchar NOT NULL, "encrypted_credential_2" varchar, "encrypted_refresh_token" varchar, "isConnected" boolean NOT NULL DEFAULT (0), CONSTRAINT "FK_c578a052ccc0f3edc20a55744f2" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_lms_connections"("id", "tenantId", "provider", "apiUrl", "encrypted_credential_1", "encrypted_credential_2", "encrypted_refresh_token", "isConnected") SELECT "id", "tenantId", "provider", "apiUrl", "encrypted_credential_1", "encrypted_credential_2", "encrypted_refresh_token", "isConnected" FROM "lms_connections"`);
        await queryRunner.query(`DROP TABLE "lms_connections"`);
        await queryRunner.query(`ALTER TABLE "temporary_lms_connections" RENAME TO "lms_connections"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a1b6fdd388caeacedb13649e72" ON "lms_connections" ("tenantId", "provider") `);
        await queryRunner.query(`CREATE TABLE "temporary_books" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "title" varchar NOT NULL, "author" varchar NOT NULL, "isbn" varchar, "status" varchar NOT NULL DEFAULT ('available'), CONSTRAINT "FK_81dcaa0c893e0b30e84b1d117d5" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_books"("id", "tenantId", "title", "author", "isbn", "status") SELECT "id", "tenantId", "title", "author", "isbn", "status" FROM "books"`);
        await queryRunner.query(`DROP TABLE "books"`);
        await queryRunner.query(`ALTER TABLE "temporary_books" RENAME TO "books"`);
        await queryRunner.query(`CREATE TABLE "temporary_fees" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "studentId" varchar NOT NULL, "amount" decimal(10,2) NOT NULL, "dueDate" datetime NOT NULL, "status" varchar NOT NULL DEFAULT ('unpaid'), CONSTRAINT "FK_7cac716bf2aef4abade8c5cd926" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_fees"("id", "tenantId", "studentId", "amount", "dueDate", "status") SELECT "id", "tenantId", "studentId", "amount", "dueDate", "status" FROM "fees"`);
        await queryRunner.query(`DROP TABLE "fees"`);
        await queryRunner.query(`ALTER TABLE "temporary_fees" RENAME TO "fees"`);
        await queryRunner.query(`CREATE TABLE "temporary_expenses" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "category" varchar NOT NULL, "amount" decimal(10,2) NOT NULL, "date" datetime NOT NULL, "description" varchar, CONSTRAINT "FK_f754faa125acaf008866b6635bc" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_expenses"("id", "tenantId", "category", "amount", "date", "description") SELECT "id", "tenantId", "category", "amount", "date", "description" FROM "expenses"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`ALTER TABLE "temporary_expenses" RENAME TO "expenses"`);
        await queryRunner.query(`CREATE TABLE "temporary_examinations" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "subjectId" varchar NOT NULL, "date" datetime NOT NULL, "totalMarks" decimal(5,2) NOT NULL, CONSTRAINT "FK_42f928c43d916d555e527c1d0b5" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_examinations"("id", "tenantId", "name", "subjectId", "date", "totalMarks") SELECT "id", "tenantId", "name", "subjectId", "date", "totalMarks" FROM "examinations"`);
        await queryRunner.query(`DROP TABLE "examinations"`);
        await queryRunner.query(`ALTER TABLE "temporary_examinations" RENAME TO "examinations"`);
        await queryRunner.query(`CREATE TABLE "temporary_messages" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "senderId" varchar NOT NULL, "recipientId" varchar NOT NULL, "content" text NOT NULL, "sentAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP), CONSTRAINT "FK_809cf06e658568d5579aa335cb5" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_messages"("id", "tenantId", "senderId", "recipientId", "content", "sentAt") SELECT "id", "tenantId", "senderId", "recipientId", "content", "sentAt" FROM "messages"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`ALTER TABLE "temporary_messages" RENAME TO "messages"`);
        await queryRunner.query(`CREATE TABLE "temporary_calendar_events" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "title" varchar NOT NULL, "start" datetime NOT NULL, "end" datetime NOT NULL, "description" varchar, CONSTRAINT "FK_308935e3c4a04f451e6cd983ddc" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_calendar_events"("id", "tenantId", "title", "start", "end", "description") SELECT "id", "tenantId", "title", "start", "end", "description" FROM "calendar_events"`);
        await queryRunner.query(`DROP TABLE "calendar_events"`);
        await queryRunner.query(`ALTER TABLE "temporary_calendar_events" RENAME TO "calendar_events"`);
        await queryRunner.query(`CREATE TABLE "temporary_attendance" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "studentId" varchar NOT NULL, "classLevelId" varchar NOT NULL, "date" datetime NOT NULL, "status" varchar NOT NULL, CONSTRAINT "FK_180d196307c19bf2f3adcf04dc6" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION, CONSTRAINT "FK_120e1c6edcec4f8221f467c8039" FOREIGN KEY ("studentId") REFERENCES "students" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_attendance"("id", "tenantId", "studentId", "classLevelId", "date", "status") SELECT "id", "tenantId", "studentId", "classLevelId", "date", "status" FROM "attendance"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`ALTER TABLE "temporary_attendance" RENAME TO "attendance"`);
        await queryRunner.query(`CREATE TABLE "temporary_subjects" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "classLevel" varchar NOT NULL, "teacherId" varchar, CONSTRAINT "FK_f382f7fa7a7084e487981938b53" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_subjects"("id", "tenantId", "name", "classLevel", "teacherId") SELECT "id", "tenantId", "name", "classLevel", "teacherId" FROM "subjects"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
        await queryRunner.query(`ALTER TABLE "temporary_subjects" RENAME TO "subjects"`);
        await queryRunner.query(`CREATE TABLE "temporary_grading_scales" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "grade" varchar NOT NULL, "minMark" decimal(5,2) NOT NULL, "maxMark" decimal(5,2) NOT NULL, "gradePoint" decimal(5,2) NOT NULL, "remarks" varchar, CONSTRAINT "FK_82a7efd59f60db9b3f9d8f9ebc2" FOREIGN KEY ("tenantId") REFERENCES "tenants" ("id") ON DELETE NO ACTION ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_grading_scales"("id", "tenantId", "grade", "minMark", "maxMark", "gradePoint", "remarks") SELECT "id", "tenantId", "grade", "minMark", "maxMark", "gradePoint", "remarks" FROM "grading_scales"`);
        await queryRunner.query(`DROP TABLE "grading_scales"`);
        await queryRunner.query(`ALTER TABLE "temporary_grading_scales" RENAME TO "grading_scales"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "grading_scales" RENAME TO "temporary_grading_scales"`);
        await queryRunner.query(`CREATE TABLE "grading_scales" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "grade" varchar NOT NULL, "minMark" decimal(5,2) NOT NULL, "maxMark" decimal(5,2) NOT NULL, "gradePoint" decimal(5,2) NOT NULL, "remarks" varchar)`);
        await queryRunner.query(`INSERT INTO "grading_scales"("id", "tenantId", "grade", "minMark", "maxMark", "gradePoint", "remarks") SELECT "id", "tenantId", "grade", "minMark", "maxMark", "gradePoint", "remarks" FROM "temporary_grading_scales"`);
        await queryRunner.query(`DROP TABLE "temporary_grading_scales"`);
        await queryRunner.query(`ALTER TABLE "subjects" RENAME TO "temporary_subjects"`);
        await queryRunner.query(`CREATE TABLE "subjects" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "classLevel" varchar NOT NULL, "teacherId" varchar)`);
        await queryRunner.query(`INSERT INTO "subjects"("id", "tenantId", "name", "classLevel", "teacherId") SELECT "id", "tenantId", "name", "classLevel", "teacherId" FROM "temporary_subjects"`);
        await queryRunner.query(`DROP TABLE "temporary_subjects"`);
        await queryRunner.query(`ALTER TABLE "attendance" RENAME TO "temporary_attendance"`);
        await queryRunner.query(`CREATE TABLE "attendance" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "studentId" varchar NOT NULL, "classLevelId" varchar NOT NULL, "date" datetime NOT NULL, "status" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "attendance"("id", "tenantId", "studentId", "classLevelId", "date", "status") SELECT "id", "tenantId", "studentId", "classLevelId", "date", "status" FROM "temporary_attendance"`);
        await queryRunner.query(`DROP TABLE "temporary_attendance"`);
        await queryRunner.query(`ALTER TABLE "calendar_events" RENAME TO "temporary_calendar_events"`);
        await queryRunner.query(`CREATE TABLE "calendar_events" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "title" varchar NOT NULL, "start" datetime NOT NULL, "end" datetime NOT NULL, "description" varchar)`);
        await queryRunner.query(`INSERT INTO "calendar_events"("id", "tenantId", "title", "start", "end", "description") SELECT "id", "tenantId", "title", "start", "end", "description" FROM "temporary_calendar_events"`);
        await queryRunner.query(`DROP TABLE "temporary_calendar_events"`);
        await queryRunner.query(`ALTER TABLE "messages" RENAME TO "temporary_messages"`);
        await queryRunner.query(`CREATE TABLE "messages" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "senderId" varchar NOT NULL, "recipientId" varchar NOT NULL, "content" text NOT NULL, "sentAt" datetime NOT NULL DEFAULT (CURRENT_TIMESTAMP))`);
        await queryRunner.query(`INSERT INTO "messages"("id", "tenantId", "senderId", "recipientId", "content", "sentAt") SELECT "id", "tenantId", "senderId", "recipientId", "content", "sentAt" FROM "temporary_messages"`);
        await queryRunner.query(`DROP TABLE "temporary_messages"`);
        await queryRunner.query(`ALTER TABLE "examinations" RENAME TO "temporary_examinations"`);
        await queryRunner.query(`CREATE TABLE "examinations" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "subjectId" varchar NOT NULL, "date" datetime NOT NULL, "totalMarks" decimal(5,2) NOT NULL)`);
        await queryRunner.query(`INSERT INTO "examinations"("id", "tenantId", "name", "subjectId", "date", "totalMarks") SELECT "id", "tenantId", "name", "subjectId", "date", "totalMarks" FROM "temporary_examinations"`);
        await queryRunner.query(`DROP TABLE "temporary_examinations"`);
        await queryRunner.query(`ALTER TABLE "expenses" RENAME TO "temporary_expenses"`);
        await queryRunner.query(`CREATE TABLE "expenses" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "category" varchar NOT NULL, "amount" decimal(10,2) NOT NULL, "date" datetime NOT NULL, "description" varchar)`);
        await queryRunner.query(`INSERT INTO "expenses"("id", "tenantId", "category", "amount", "date", "description") SELECT "id", "tenantId", "category", "amount", "date", "description" FROM "temporary_expenses"`);
        await queryRunner.query(`DROP TABLE "temporary_expenses"`);
        await queryRunner.query(`ALTER TABLE "fees" RENAME TO "temporary_fees"`);
        await queryRunner.query(`CREATE TABLE "fees" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "studentId" varchar NOT NULL, "amount" decimal(10,2) NOT NULL, "dueDate" datetime NOT NULL, "status" varchar NOT NULL DEFAULT ('unpaid'))`);
        await queryRunner.query(`INSERT INTO "fees"("id", "tenantId", "studentId", "amount", "dueDate", "status") SELECT "id", "tenantId", "studentId", "amount", "dueDate", "status" FROM "temporary_fees"`);
        await queryRunner.query(`DROP TABLE "temporary_fees"`);
        await queryRunner.query(`ALTER TABLE "books" RENAME TO "temporary_books"`);
        await queryRunner.query(`CREATE TABLE "books" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "title" varchar NOT NULL, "author" varchar NOT NULL, "isbn" varchar, "status" varchar NOT NULL DEFAULT ('available'))`);
        await queryRunner.query(`INSERT INTO "books"("id", "tenantId", "title", "author", "isbn", "status") SELECT "id", "tenantId", "title", "author", "isbn", "status" FROM "temporary_books"`);
        await queryRunner.query(`DROP TABLE "temporary_books"`);
        await queryRunner.query(`DROP INDEX "IDX_a1b6fdd388caeacedb13649e72"`);
        await queryRunner.query(`ALTER TABLE "lms_connections" RENAME TO "temporary_lms_connections"`);
        await queryRunner.query(`CREATE TABLE "lms_connections" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "provider" varchar CHECK( "provider" IN ('moodle','google_classroom','canvas') ) NOT NULL, "apiUrl" varchar NOT NULL, "encrypted_credential_1" varchar NOT NULL, "encrypted_credential_2" varchar, "encrypted_refresh_token" varchar, "isConnected" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "lms_connections"("id", "tenantId", "provider", "apiUrl", "encrypted_credential_1", "encrypted_credential_2", "encrypted_refresh_token", "isConnected") SELECT "id", "tenantId", "provider", "apiUrl", "encrypted_credential_1", "encrypted_credential_2", "encrypted_refresh_token", "isConnected" FROM "temporary_lms_connections"`);
        await queryRunner.query(`DROP TABLE "temporary_lms_connections"`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a1b6fdd388caeacedb13649e72" ON "lms_connections" ("tenantId", "provider") `);
        await queryRunner.query(`ALTER TABLE "pending_payments" RENAME TO "temporary_pending_payments"`);
        await queryRunner.query(`CREATE TABLE "pending_payments" ("id" varchar PRIMARY KEY NOT NULL, "amount" integer NOT NULL, "method" varchar CHECK( "method" IN ('stripe','mpesa','bank_transfer') ) NOT NULL, "reference" varchar NOT NULL, "plan" varchar CHECK( "plan" IN ('free','basic','standard','premium','enterprise') ), "isApproved" boolean NOT NULL DEFAULT (0), "createdAt" datetime NOT NULL DEFAULT (datetime('now')), "updatedAt" datetime NOT NULL DEFAULT (datetime('now')), "tenantId" varchar)`);
        await queryRunner.query(`INSERT INTO "pending_payments"("id", "amount", "method", "reference", "plan", "isApproved", "createdAt", "updatedAt", "tenantId") SELECT "id", "amount", "method", "reference", "plan", "isApproved", "createdAt", "updatedAt", "tenantId" FROM "temporary_pending_payments"`);
        await queryRunner.query(`DROP TABLE "temporary_pending_payments"`);
        await queryRunner.query(`ALTER TABLE "payrolls" RENAME TO "temporary_payrolls"`);
        await queryRunner.query(`CREATE TABLE "payrolls" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "staffId" varchar NOT NULL, "salary" decimal(10,2) NOT NULL, "payDate" datetime NOT NULL, "status" varchar NOT NULL DEFAULT ('unpaid'))`);
        await queryRunner.query(`INSERT INTO "payrolls"("id", "tenantId", "staffId", "salary", "payDate", "status") SELECT "id", "tenantId", "staffId", "salary", "payDate", "status" FROM "temporary_payrolls"`);
        await queryRunner.query(`DROP TABLE "temporary_payrolls"`);
        await queryRunner.query(`ALTER TABLE "report_cards" RENAME TO "temporary_report_cards"`);
        await queryRunner.query(`CREATE TABLE "report_cards" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "studentId" varchar NOT NULL, "examinationId" varchar NOT NULL, "marks" decimal(5,2) NOT NULL, "grade" varchar, "remarks" varchar)`);
        await queryRunner.query(`INSERT INTO "report_cards"("id", "tenantId", "studentId", "examinationId", "marks", "grade", "remarks") SELECT "id", "tenantId", "studentId", "examinationId", "marks", "grade", "remarks" FROM "temporary_report_cards"`);
        await queryRunner.query(`DROP TABLE "temporary_report_cards"`);
        await queryRunner.query(`ALTER TABLE "staff" RENAME TO "temporary_staff"`);
        await queryRunner.query(`CREATE TABLE "staff" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "role" varchar NOT NULL, "email" varchar NOT NULL, "phone" varchar, CONSTRAINT "UQ_902985a964245652d5e3a0f5f6a" UNIQUE ("email"))`);
        await queryRunner.query(`INSERT INTO "staff"("id", "tenantId", "firstName", "lastName", "role", "email", "phone") SELECT "id", "tenantId", "firstName", "lastName", "role", "email", "phone" FROM "temporary_staff"`);
        await queryRunner.query(`DROP TABLE "temporary_staff"`);
        await queryRunner.query(`ALTER TABLE "students" RENAME TO "temporary_students"`);
        await queryRunner.query(`CREATE TABLE "students" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "firstName" varchar NOT NULL, "lastName" varchar NOT NULL, "registrationNumber" varchar, "classLevelId" varchar, "sectionId" varchar, "academicYearId" varchar, "status" varchar NOT NULL DEFAULT ('Active'), "parentId" varchar)`);
        await queryRunner.query(`INSERT INTO "students"("id", "tenantId", "firstName", "lastName", "registrationNumber", "classLevelId", "sectionId", "academicYearId", "status", "parentId") SELECT "id", "tenantId", "firstName", "lastName", "registrationNumber", "classLevelId", "sectionId", "academicYearId", "status", "parentId" FROM "temporary_students"`);
        await queryRunner.query(`DROP TABLE "temporary_students"`);
        await queryRunner.query(`ALTER TABLE "academic_years" RENAME TO "temporary_academic_years"`);
        await queryRunner.query(`CREATE TABLE "academic_years" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "startDate" date NOT NULL, "endDate" date NOT NULL, "isCurrent" boolean NOT NULL DEFAULT (0))`);
        await queryRunner.query(`INSERT INTO "academic_years"("id", "tenantId", "name", "startDate", "endDate", "isCurrent") SELECT "id", "tenantId", "name", "startDate", "endDate", "isCurrent" FROM "temporary_academic_years"`);
        await queryRunner.query(`DROP TABLE "temporary_academic_years"`);
        await queryRunner.query(`ALTER TABLE "class_levels" RENAME TO "temporary_class_levels"`);
        await queryRunner.query(`CREATE TABLE "class_levels" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "description" varchar)`);
        await queryRunner.query(`INSERT INTO "class_levels"("id", "tenantId", "name", "description") SELECT "id", "tenantId", "name", "description" FROM "temporary_class_levels"`);
        await queryRunner.query(`DROP TABLE "temporary_class_levels"`);
        await queryRunner.query(`ALTER TABLE "sections" RENAME TO "temporary_sections"`);
        await queryRunner.query(`CREATE TABLE "sections" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "classLevelId" varchar NOT NULL, "room" varchar)`);
        await queryRunner.query(`INSERT INTO "sections"("id", "tenantId", "name", "classLevelId", "room") SELECT "id", "tenantId", "name", "classLevelId", "room" FROM "temporary_sections"`);
        await queryRunner.query(`DROP TABLE "temporary_sections"`);
        await queryRunner.query(`ALTER TABLE "timetable_entries" RENAME TO "temporary_timetable_entries"`);
        await queryRunner.query(`CREATE TABLE "timetable_entries" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "classLevel" varchar NOT NULL, "dayOfWeek" varchar NOT NULL, "startTime" varchar NOT NULL, "endTime" varchar NOT NULL, "subjectId" varchar NOT NULL, "teacherId" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "timetable_entries"("id", "tenantId", "classLevel", "dayOfWeek", "startTime", "endTime", "subjectId", "teacherId") SELECT "id", "tenantId", "classLevel", "dayOfWeek", "startTime", "endTime", "subjectId", "teacherId" FROM "temporary_timetable_entries"`);
        await queryRunner.query(`DROP TABLE "temporary_timetable_entries"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" RENAME TO "temporary_role_permissions"`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "role" varchar CHECK( "role" IN ('super_admin','admin','teacher','parent') ) NOT NULL, "permissionId" varchar NOT NULL)`);
        await queryRunner.query(`INSERT INTO "role_permissions"("id", "tenantId", "role", "permissionId") SELECT "id", "tenantId", "role", "permissionId" FROM "temporary_role_permissions"`);
        await queryRunner.query(`DROP TABLE "temporary_role_permissions"`);
        await queryRunner.query(`ALTER TABLE "permissions" RENAME TO "temporary_permissions"`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "name" varchar NOT NULL, "description" varchar)`);
        await queryRunner.query(`INSERT INTO "permissions"("id", "tenantId", "name", "description") SELECT "id", "tenantId", "name", "description" FROM "temporary_permissions"`);
        await queryRunner.query(`DROP TABLE "temporary_permissions"`);
        await queryRunner.query(`ALTER TABLE "users" RENAME TO "temporary_users"`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar PRIMARY KEY NOT NULL, "tenantId" varchar NOT NULL, "username" varchar NOT NULL, "password_hash" varchar NOT NULL, "password_reset_token" varchar, "password_reset_expires" datetime, "role" varchar CHECK( "role" IN ('super_admin','admin','teacher','parent') ) NOT NULL DEFAULT ('parent'), CONSTRAINT "UQ_fe0bb3f6520ee0469504521e710" UNIQUE ("username"))`);
        await queryRunner.query(`INSERT INTO "users"("id", "tenantId", "username", "password_hash", "password_reset_token", "password_reset_expires", "role") SELECT "id", "tenantId", "username", "password_hash", "password_reset_token", "password_reset_expires", "role" FROM "temporary_users"`);
        await queryRunner.query(`DROP TABLE "temporary_users"`);
        await queryRunner.query(`DROP TABLE "grading_scales"`);
        await queryRunner.query(`DROP TABLE "subjects"`);
        await queryRunner.query(`DROP TABLE "attendance"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TABLE "calendar_events"`);
        await queryRunner.query(`DROP TABLE "messages"`);
        await queryRunner.query(`DROP TABLE "examinations"`);
        await queryRunner.query(`DROP TABLE "expenses"`);
        await queryRunner.query(`DROP TABLE "fees"`);
        await queryRunner.query(`DROP TABLE "books"`);
        await queryRunner.query(`DROP INDEX "IDX_a1b6fdd388caeacedb13649e72"`);
        await queryRunner.query(`DROP TABLE "lms_connections"`);
        await queryRunner.query(`DROP TABLE "pending_payments"`);
        await queryRunner.query(`DROP TABLE "payrolls"`);
        await queryRunner.query(`DROP TABLE "report_cards"`);
        await queryRunner.query(`DROP TABLE "staff"`);
        await queryRunner.query(`DROP TABLE "students"`);
        await queryRunner.query(`DROP TABLE "academic_years"`);
        await queryRunner.query(`DROP TABLE "class_levels"`);
        await queryRunner.query(`DROP TABLE "sections"`);
        await queryRunner.query(`DROP TABLE "subscription_plans"`);
        await queryRunner.query(`DROP TABLE "timetable_entries"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "tenants"`);
    }

}
